name: Linux GCC Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Declare Git Variables
        id: git_vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Install dependencies
        run: bash ./install_linux_requirements.sh
      - name: CMake Configure
        run: cmake --preset linux-gcc-x64
      - name: Cmake Build Debug
        run: cmake --build --preset linux-gcc-x64-debug
      - name: Cmake Build Profile
        run: cmake --build --preset linux-gcc-x64-relwithdebinfo
      - name: Cmake Build Release
        run: cmake --build --preset linux-gcc-x64-release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: gamedb-linux-gcc-${{ steps.git_vars.outputs.sha_short }}
          path: out
          retention-days: 5
