name: Windows MSVC Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Declare Git Variables
        id: git_vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Setup Microsoft build
        uses: microsoft/setup-msbuild@v1.0.3
      - name: Setup MSVC development tools
        uses: ilammy/msvc-dev-cmd@v1
      - name: CMake Configure
        run: cmake --preset windows-msvc-x64
      - name: Cmake Build Debug
        run: cmake --build --preset windows-msvc-x64-debug
      - name: Cmake Build Profile
        run: cmake --build --preset windows-msvc-x64-relwithdebinfo
      - name: Cmake Build Release
        run: cmake --build --preset windows-msvc-x64-release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: gamedb-windows-msvc-${{ steps.git_vars.outputs.sha_short }}
          path: out
          retention-days: 5
